version: '3.7'

services:
  postgres:
    image: postgres:11.3-alpine
    container_name: vscode_remote_postgres
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ./docker/data/postgres:/var/lib/postgres/data